config/routes.rb
Rails.application.routes.draw do
  devise_for :offices
  devise_for :users

  root to: "top#index"
  resources :informations do
    resources :comments, only: :create
    resources :user_comments, only: :create
  end
  resources :offices, only: [:index,:show]
end

app/models/information.rb
class Information < ApplicationRecord
  validates :text,:name, presence: true
  belongs_to :office
  has_many :comments
  has_many :user_comments  # user_commentsテーブルとのアソシエーション
  mount_uploader :image, ImageUploader
end

app/controllers/informations_controller.rb
class InformationsController < ApplicationController
  before_action :set_information, only: [:edit, :show]
  # before_action :move_to_index, except: [:index, :show]
  def index
    @informations = Information.includes(:office)
  end

  def new
    @information = Information.new
  end

  def create
    @information = Information.new(information_params)
    if @information.save
      redirect_to informations_path(@information), notice: '投稿が完了しました'
    else
      flash.now[:alert] = '事業所名とテキストを入力してください'
      render :new
    end
  end

  def destroy
    information = Information.find(params[:id])
    information.destroy
  end

  def edit
  end

  def update
    information = Information.find(params[:id])
    information.update(information_params)
  end
  
  def show
    @comment = Comment.new
    @comments = @information.comments.includes(:office).order(id: "DESC")
    @user_comment = UserComment.new
    @user_comments = @information.user_comments.includes(:user).order(id: "DESC")
  end

  private
  def information_params
    params.require(:information).permit(:name, :text, :prefecture, :city,:postal_code,:house_number,:office_tel, :image ).merge(office_id: current_office.id)
  end

  def set_information
    @information = Information.find(params[:id])
    # @information = Information.find(params[:office_id])
  end

  # def move_to_index
  #   # redirect_to action: :index unless user_signed_in?
  #   # redirect_to action: :index unless office_signed_in?
  # end
  
end

app/helpers/informations_helper.rb
module InformationsHelper
end

app/views/informations/create.html.haml
.contents
  .contents__success
    送信が完了しました。
  .contents__btn 
    = link_to informations_path(@information),class:"edit-btn" do
      %span<>
      ホーム画面へ戻る

app/views/informations/destroy.html.haml
.contents
  .contents__success
    削除が完了しました。
  .contents__btn 
    = link_to informations_path, class:"edit-btn" do
      ホーム画面へ戻る

app/views/informations/edit.html.haml
.edit_contents
  = render 'offices/shared/user_header'
  .edit_contents__header
    編集フォーム
  .edit_contents__container
    = form_with(model: @information, url:".",local: true)  do |form|
      = form.file_field :image, placeholder: "画像のurlを貼り付けてください", class: "text_field"
      = form.text_area :text, placeholder: "・事業所の紹介\n・事業所の特色\n・空き情報\n・アピールポイント\nなどを入力して下さい" , rows: "10",class:"text_area"
      = form.submit "変更する", class: "send"

app/views/informations/index.html.haml
.info
  = render 'offices/shared/header'
  .info__image
    .info__image__left
      %p 　　　　　　　　　　　　　　　　
      %p Wel.Net...
      %p 　　　　　　　　　　　　　　　　
      %p 介護・保育・医療など
      %p 　　　　　　　　　　　　　　　　
      %p 福祉全般の
      %p 　　　　　　　　　　　　　　　　
      %p 総合情報サイトです
    .info__image__right
      %p ↑↑　　↑↑　　↑↑　　
      %p 　　　　　　　　　　　　　　　　
      %p サービスをお探しの方は
      %p 上記「利用者様より」新規登録
      %p をお願いいたします
      %p ---------------------------------------------------
      %p 　　　　　　　　　　　　　　　　
      %p サービスのご紹介をしてくださる
      %p 事業所様は上記「事業者様」より
      %p 新規登録をお願いいたします

    %div.slick
      %div
        %img{alt: "介護",src: "18df9e57223a7c1b44149b83db9593a0_w.jpg"}
      %div
        %img{alt: "保育",src: "9497efd44913e48ae7434b0a08c00956_w.jpg"}
      %div
        %img{alt: "相談",src: "0d9c20fe032ce770d4ae11ce85851b42_w.jpg"}
      %div
        %img{alt: "家族",src: "00a315137469b1ef00bcaba1b3b22e9e_t.jpeg"}
      %div
        %img{alt: "老夫婦",src: "e4a02113f81d15c24c0311fe6f17cbb5_w.jpg"}
      %div
        %img{alt: "家",src: "eb6935419a2d65a242f8f2891d48d415_w.jpg"}
  .info__contents
    .info__contents__left
      .info__contents__left__header
        介護
      - @informations.each do |information|
        .info__contents__left__list
          .info__contents__left__list__box
            .info__contents__left__list__box__name
              = link_to information_path(information.id), method: :get do
                =information.name
                さんの投稿
            .info__contents__left__list__box__cities
              %p= information.created_at.strftime("%Y年%m月%d日")
              %p= information.prefecture
              %p= information.city
    .info__contents__center
      .info__contents__center__header
        保育
      - @informations.each do |information|
        .info__contents__center__list
          .info__contents__center__list__box
            .info__contents__center__list__box__name
              = link_to information_path(information.id), method: :get do
                =information.name
                さんの投稿
            .info__contents__center__list__box__cities
              %p= information.created_at.strftime("%Y年%m月%d日")
              %p= information.prefecture
              %p= information.city
    .info__contents__right
      .info__contents__right__header
        障がい
      - @informations.each do |information|
        .info__contents__right__list
          .info__contents__right__list__box
            .info__contents__right__list__box__name
              = link_to information_path(information.id), method: :get do
                =information.name
                さんの投稿
            .info__contents__right__list__box__cities
              %p= information.created_at.strftime("%Y年%m月%d日")
              %p= information.prefecture
              %p= information.city
  

app/views/informations/new.html.haml
.new_contents
  = render 'offices/shared/user_header'
  .new_contents__header
    事業所紹介・入力フォーム
  .new_contents__containaer
    = form_with(model:@information, url:informations_path,metod: :post,local: true, class:"form" )  do |form|
      = form.text_field :name,placeholder: "事業所名を入力して下さい" ,class:"text_field"
      = form.text_field :office_tel, placeholder: "電話番号", class: "text_field"
      = form.text_field :postal_code, placeholder: "郵便番号", class: "text_field"
      = form.text_field :prefecture, placeholder: "都道府県名を入力してください（例）滋賀県", class: "text_field"
      = form.text_field :city, placeholder: "市町村名を入力してください（例）大津市", class: "text_field"
      = form.text_field :house_number, placeholder: "番地", class: "text_field"
      = form.file_field :image, placeholder: "画像のurlを貼り付けてください", class: "text_field"
      = form.text_area :text, placeholder: "・事業所の紹介\n・事業所の特色\n・空き情報\n・アピールポイント\nなどを入力して下さい" ,class:"text_area"
      = form.submit "投稿する", class: "send"

app/views/informations/show.html.haml
.show-content
  = render 'offices/shared/user_header'
  .show-content__post
    .show-content__post__more
      .show-content__post__more__name
        %p= @information.name
        %p  さんの投稿
      .show-content__post__more__place
        %p  所在地：
        %p= @information.prefecture
        %p= @information.city
      - if office_signed_in? && current_office.id == @information.office_id
        .show-content__post__more__edit
          = link_to edit_information_path, method: :get ,class: "edit" do
            編集
          = link_to information_path, method: :delete  ,class:"delete"do
            削除
    .show-content__post__container        
      .show-content__post__container__text
        = simple_format(@information.text)
      .show-content__post__container__image
        = image_tag @information.image.url ,size:250 if @information.image.present?

    .show-content__post__comment
      - if current_office 
        = form_with(model: [@information, @comment], url:information_comments_path(@information.id) , local: true,id:"new_comment") do |form|
          = form.text_area :text, placeholder: "コメントを入力してください",class:"form"
          = form.submit "コメント送信",class:"send"
      - elsif current_user
        = form_with(model: [@information, @user_comment], url:information_user_comments_path(@information.id) , local: true,id:"new_comment") do |form|
          = form.text_area :text, placeholder: "コメントを入力してください",class:"form"
          = form.submit "コメント送信",class:"send"
      - else
        %p ※※※ コメントの投稿には新規登録/ログインが必要です ※※※
    .show-content__post__show
      .show-content__post__show__header
        ＜コメント一覧＞
      - if @comments
        - @comments.each do |comment|
          = comment.office.office_name 
          さん
          = comment.created_at.strftime("%Y年%m月%d日")
          ：
          = simple_format(comment.text)
      .show-content__post__show__header
      - if @user_comments
        - @user_comments.each do |user_comment|
          = user_comment.user.nickname 
          さん
          = user_comment.created_at.strftime("%Y年%m月%d日")
          ：
          = simple_format(user_comment.text)

app/views/informations/update.html.haml
.contents
  .contents__success
    更新が完了しました。
  .contents__btn 
    = link_to informations_path, class:"edit-btn" do
      ホーム画面へ戻る